### ISSUE TITLE
Can't create any region. (Missing Reqs)

### ISSUE THREAD

**Issue by Louis-BloodRose** [Multitallented/Civs#10]
With the new version (Fix for explosions), I can't place any region, even the ones without Block Reqs.

How to replicate:

- Create any building.yml with empty reqs for constructing / or with reqs.
- Buy it.
- Try to place. 
- Error, says you can't place because its missing reqs even when you fulfill them.

If you don't meet the Reqs, it will say normally on chat. But the error is when you have and it says you can't place.

**Comment by Multitallented** [comment]
I've released another fix. Thanks for testing this
