### ISSUE TITLE
I can't destroy buildings without owners.

### ISSUE THREAD

**Issue by NemoCZmoravia** [Multitallented/Civs#109]
So I have a socialist city. I created a flowershop and removed myself as an owner. I am the owner of the town, but I can't add my self as an owner of the flowershop so I can't remove it.

**Comment by NemoCZmoravia** [comment]
Also I couldn't set anyone else as an owner before that. And I think, that's good because I see that if you could change owner of the shop, It could break the limit of how many of them you can build.

possible solution: I think, that anyone should be able to break a building without owners.

**Comment by Multitallented** [comment]
This is a bug that I will fix in v1.6.7

**Comment by NemoCZmoravia** [comment]
This is still a bug in v1.6.7.

**Comment by Multitallented** [comment]
Fixed in v1.6.8
