### ISSUE TITLE
Arrow traps shoot even when they are not loaded with arrows.

### ISSUE THREAD

**Issue by NemoCZmoravia** [Multitallented/Civs#121]
PaperSpigot 201
Civs 1.6.7

**Comment by RumiExMachina** [comment]
Are you sure its not a LvL 3 Arrow Turret?
The lvl 3 does not require arrows to shoot.

**Comment by NemoCZmoravia** [comment]
It was LvL 1.

**Comment by Multitallented** [comment]
Yes they shoot at mobs even without arrows. This is intentional
