### ISSUE TITLE
Revert region to wilderness on destroy

### ISSUE THREAD

**Issue by TofPlays** [Multitallented/Civs#139]
An option for a region to revert back to wilderness. 
   So it makes a snapshot of the area when the region is created. Then when the region is destroyed, it will slowly revert back to however it was. Towny does this if you wanna see an example, look for a config option "revert_on_unclaim"
   
   Here's a crazier idea:
The option for a region to turn into a ruin when destroyed. 
   So when a region is destroyed, it's blocks turn into random cobble/gravel but everything above 3 block height destroyed, so ceilings and walls aren't left hanging too high. And it will look interesting to see a former house, now a ruin looking like a floor plan, and wonder: What happened here?

**Comment by Multitallented** [comment]
Sounds fun, but I don't want to make this a feature. I fear that people will accidentally destroy buildings and have the blocks get deleted too. When a town is destroyed, it is usually blown up. TNT leaves nice craters and ruins. If you want to make this feature, then I would be happy to accept a pull request
