### ISSUE TITLE
Region upkeep command Placeholders

### ISSUE THREAD

**Issue by TofPlays** [Multitallented/Civs#147]
New placeholders that will display coordinates of the region that ran a command on cycle.
%civs_region_x%
%civs_region_y%
%civs_region_z%

The reason for this suggestion is that I wanted to spawn a custom mob right on the region when it cycles.

**Comment by Multitallented** [comment]
Added in the next update. Variables are $region_x$, etc.

**Comment by CalebGitBritannia** [comment]
Nice
