### ISSUE TITLE
Shop recipes change slightly.

### ISSUE THREAD

**Issue by DillFrescott** [Multitallented/Civs#155]
I noticed that when I try to make a structure such as the coal shop, purifier, leather shop, etc. The recipe changes slightly sometimes even if i try to place the chest in the same exact spot. 

I originally thought that the recipe changing was because of trying to place the chest in various spots because some of the blocks could be present in the area, but I've had the recipe change even while trying to place it in the same spot with no changes made to the surrounding blocks.

**Comment by Multitallented** [comment]
Fixed in v1.6.11
