### ISSUE TITLE
Starter book given after every login

### ISSUE THREAD

**Issue by Jose-Paulo-FaD** [Multitallented/Civs#17]
Every time I login to the server I receive an additional starter book, even if I already have one in my inventory.

I looked at the code and found the possible culprit. The Util.isStarterBook function returns the following statement to test if the player already has an starter book:

`return itemStack.getItemMeta().getLore().get(0).equals("starter-book");`

The "starter-book" lore has a color in-game, which means the string it returns has a color code in it, so the comparison between it and "starter-book" is false and the players receives another book, even if he already has one.

I used essentials to give myself a book that had no color in the "starter-book" lore and the bug went away. So the solution is to strip the color from the lore's string before doing the comparison.

**Comment by Multitallented** [comment]
Fixed. Will be in the next update.
