### ISSUE TITLE
Submission for a server using civs

### ISSUE THREAD

**Issue by PaintsplattersMC** [Multitallented/Civs#215]
Server Name: Realmportal
 Owner: Paintsplatters
 Version: 1.17.1 native (1.18.2 client recommended) 
 IP Address: realmportalmc.xyz
 Discord Guild Link:  https://discord.gg/eVvG4ad
 Owner Contact Discord: @ Paintsplatters#8819
 
 (there is a lot more going on that just the civs plugin, please let me know if you have any concerns or questions)

**Comment by RumiExMachina** [comment]
Added and closed.
