### ISSUE TITLE
Four different requests.

### ISSUE THREAD

**Issue by ZeekPlayz** [Multitallented/Civs#24]
Here are a couple requests that would make the plugin more configurable/more features:

1. Config to disable colonies (outposts) from going rogue

2. A better/enhanced system so that people can have multiple towns under one "rule"

3. NPC guards that could use certain structures as e.g archer towers or a gate to defend.

4. More in-depth siege weaponry, potentially customizable (like item) projectile types that change power damage/end block damage after power is gone etc.

very excited for this mod, I'm designing a ww2 server with it.

**Comment by Multitallented** [comment]
I won't do 3 because mob AI is really hard. Maybe down the road I'll attempt it. I'll look into doing the others

**Comment by Hellcode48** [comment]
> 
> 
> I won't do 3 because mob AI is really hard. Maybe down the road I'll attempt it. I'll look into doing the others

Use CitizensAPI rather than using a mob api
