### ISSUE TITLE
Shelters and such disappearing

### ISSUE THREAD

**Issue by deadspidervenom** [Multitallented/Civs#26]
So i place shelters shacks hamlets, they disappear randomly

**Comment by deadspidervenom** [comment]
Okay things i can Confirm disappear.

Coal Shop
Shelter
Iron Mine
Shack
Hovel

Things that dont disappear.

Potato Farm
Council Room
Settlement.

**Comment by Multitallented** [comment]
I'm not able to reproduce this issue. Are these items returning to your inventory; if you relog when these items disappear, do they reappear in your inventory or blueprints menu?

Do they disappear right away or after some time or after a restart maybe? Are you breaking these items and they don't drop (cause that's working as intended if you have civ-item-sharing: false)?

Do you have a plugin that could be disappearing these items?

**Comment by deadspidervenom** [comment]
It seems they usually disappear when i logout for a time, my guess would be something to do would chunks unloading.

However it seems different per player, as my friend coal shop has yet to vanish on them, however their shelter vanish on them.

**Comment by deadspidervenom** [comment]
Oh and its not actual disappearance, the blocks remain, like the chest and stuff, but they no longer function, and no longer have a region

**Comment by Multitallented** [comment]
Do you have any errors in the console? Do the region files still exist in the Civs/regions folder?

**Comment by deadspidervenom** [comment]
the owner and main dev of the server should of Messaged you if not ill have him post here, name should be like tadeo or taydeo

**Comment by deadspidervenom** [comment]
I think it has something to do with converting a old world to a new world.

**Comment by Multitallented** [comment]
I did not receive any follow up response from server devs. I assume this has something to do with your world conversion. I've not heard anyone else reporting any similar issues. I'll reopen this if something else comes up.
