### ISSUE TITLE
Minecart not despawning in warehouse when off track

### ISSUE THREAD

**Issue by omn0mn0m** [Multitallented/Civs#27]
Server Version: Paper 1.13.2 Build 639

When a powered rail is used to boost a minecart off the tracks when it enters the warehouse, the minecart will be stuck in the warehouse without despawning. Placing a block at the end of the track to prevent the minecart from leaving the end of the tracks fixes this.

**Comment by Multitallented** [comment]
Sounds like the minecart is exiting the region before it can be detected. Whether the minecart is on the rails or not should not matter.
