### ISSUE TITLE
It's not fair to Chinese,qwq

### ISSUE THREAD

**Issue by nikissXI** [Multitallented/Civs#30]
![image](https://user-images.githubusercontent.com/31379266/62524196-c6534900-b867-11e9-976a-84757ba4b68f.png)
![image](https://user-images.githubusercontent.com/31379266/62524247-d834ec00-b867-11e9-81b5-75eab42d9611.png)

**Comment by Multitallented** [comment]
Text wrapping does not seem to be working for Chinese because there are no spaces. I'll see what I can do. Thanks for reporting this.

**Comment by nikissXI** [comment]
Very grateful！
