### ISSUE TITLE
About jade shop and warehouse

### ISSUE THREAD

**Issue by nikissXI** [Multitallented/Civs#32]
problems:

The jade shop:

1. The jade shop's description is wrong. I place my mouse pointer on the jade shop icon , it shows that pay 144 emeralds to server per day to get $1000.
But when the jade shop was built , the jade shop show that pay 16 emeralds to server per day to get $1000.
2. The jade shop's cooldown time is far slower than other shop buildings or farm buildings.
3. When I put some emeralds (165 emeralds) into jade shop's chest nearly one day later , the shop still doesn't trade , the number of emeralds no decrease. And the money no increase.

The warehouse:
1. The warehouse is described as assigning items to the desired area, but the "cow farm" 's leathers don't enter the "leather store" chest.

(I am manually translated in this passage, there may be some errors.)
Original text below

问题描述：
一：绿宝石商店问题
1.绿宝石商店描述有误，在购买时，将鼠标移动到绿宝石商店图标上后，显示每天支出144绿宝石给服务器换取1000金币，但是当建造完绿宝石商店后，在绿宝石商店建筑页面却显示消耗16绿宝石，获得1000金币
2.绿宝石商店的“操作”按钮，其显示区域冷却时间变化远慢于其他商店建筑或农场建筑
3.将一定量的绿宝石（165个）放入“绿宝石商店”箱子里近一天后，商店并没有交易，绿宝石数量并没有减少，金币也并没有增加
二：仓库问题
1.仓库描述为分配物品到需要的区域内，但“牛农场”里的皮革并没有进入“皮革商店”的箱子

**Comment by nikissXI** [comment]
The plugin version is Civs v1.4.2-(1.14)

**Comment by Multitallented** [comment]
The jade shop doesn't sell emeralds. It sells Jade (named emeralds produced at the jade mine). Is the translation not clear?

I've fixed the translation so that it says 16 instead of 144. Thanks for catching that bug.

The jade shop and jade mine are supposed to be very slow. The reason for this is so players have time to trade jade (because you can't build a jade mine and jade shop in the same town).

You placed the leather in the warehouse, and it didn't move that leather to the leather shop?

**Comment by nikissXI** [comment]
![image](https://user-images.githubusercontent.com/31379266/63392124-e9453780-c3e7-11e9-9d9e-d70692ea064b.png)
OK，I konw what happen. The Chinese translation say that is emerald(绿宝石) , in fact, it is jade(玉).

**Comment by nikissXI** [comment]
About the warehouse, I put 14 leathers into it. But when the cooldown time arrives, the 14 leathers still in the warehouse's chest. The amount of leather shop no change.

**Comment by nikissXI** [comment]
About the jade shop and jade mine's cool down time .
It display the cool down is 30m 00s , but the time runs very slow.
For example , the cow farm's cool down time is 3m 45s , few seconds later is 3m 41s.
But the jade shop's cool down time is 29m 40s ,few minutes later just 29m 38s.
What's the problem?

**Comment by Multitallented** [comment]
I'll change the Chinese translation. I'll have to look into the jade shop cooldown. Definitely sounds bugged.

**Comment by nikissXI** [comment]
What's the meaning of "Definitely sounds bugged."
I am so sorry to my English.haha.

**Comment by nikissXI** [comment]
![image](https://user-images.githubusercontent.com/31379266/63401636-9c268d00-c40a-11e9-9d2e-b70b1259d83e.png)
![image](https://user-images.githubusercontent.com/31379266/63401776-21aa3d00-c40b-11e9-87c7-c83195308217.png)

By the way, how to use the Civs Catapult and Connon Controller?

**Comment by Multitallented** [comment]
Definitely sounds bugged means that I suspect there is a problem.

For the catapult, take the stick it drops and right click somewhere while holding it.

**Comment by nikissXI** [comment]
OK，it is very kind of you!
