### ISSUE TITLE
Menu Bug

### ISSUE THREAD

**Issue by Endothelium** [Multitallented/Civs#35]
Hello,

When you open a menu, for example civ shop -> admin category, there is an item diplaying the current category you are in, in the left corner.
If you click it, it doesnt change the current menu ( because it's only informative ), but it's still act like you opened an other menu.

So if you click on back after , you stay on the current menu. In reality you have opened the same menu multiple times so it close it but it feel like the back button did nothing.

![menu_bug](https://user-images.githubusercontent.com/11161697/64064935-f512d400-cc07-11e9-8467-68c481dd2803.gif)

**Comment by Multitallented** [comment]
This will be fixed when the custom menus update comes out
