### ISSUE TITLE
QOL Improvement - Build Area

### ISSUE THREAD

**Issue by Endothelium** [Multitallented/Civs#36]
Actually, it seems that to display your build area, you need to right click your book or blueprint to make the colors glasses appear.
It feel very weird for some of my players.

What happen it that :

- **While trying to build a blueprint they dont remember the borders of the build**, so they have to right click the blueprint to make the borders appear and open a menu for that. It is not instant and open the menu just to build feel annoying to them.

A solution would be a **right click to see blueprint menu and a left click to just show the build limits**.

- **They dont remember the center of the build**, so they start a build, then when they check if they have all the requirements, they build outside the area they want, so they dont understand why they dont meet all the blocks requirements, and many problems related to this.

A solution would be to be able to **save the center of the build**. For example, you could open the blueprint menu and save a center point my clicking an item in the menu. Like this, if they use the click i say before ( the one that just show you the area limit of your current building), it would show the border relative to where you set the center point, and not the current position. If you never set a center point, it show the border relative to your current position.

**Comment by Multitallented** [comment]
Fixed in the next update
