### ISSUE TITLE
Feature Request : Perm req for pay

### ISSUE THREAD

**Issue by Endothelium** [Multitallented/Civs#37]
Hello,

My server is a RP server. There are jobs on it ( Miner, woodcutter...).

The build pre requisite is good for this, i can let only WoodCutter player build a WoodShop for example.

But the problem is, if the player leave the Woodcutter Job and become a miner, he will still be paid for his WoodShop.

So the feature request is to stop payout someone if he doesnt meet the perm requirement.
A good feature too would be a payout multiplier depending on the permission the player have ( the WoodCutter have better payout multiplier on a WoodShop than a miner).

**Comment by Multitallented** [comment]
This will be included in the next update
