### ISSUE TITLE
CIvs items disappearing randomly

### ISSUE THREAD

**Issue by whisperer195** [Multitallented/Civs#38]
10.09 00:13:21 [Server] ERROR Could not pass event InventoryClickEvent to Civs v1.4.4
10.09 00:13:21 [Server] INFO java.lang.NullPointerException: null
10.09 00:13:21 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.RegionTypeInfoMenu.handleInteract(RegionTypeInfoMenu.java:35) ~[?:?]
10.09 00:13:21 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.Menu.onMenuInteract(Menu.java:61) ~[?:?]
10.09 00:13:21 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor648.execute(Unknown Source) ~[?:?]
10.09 00:13:21 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:991) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:21 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

10.09 00:13:28 [Server] INFO java.lang.NullPointerException: null
10.09 00:13:28 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.RegionTypeInfoMenu.handleInteract(RegionTypeInfoMenu.java:35) ~[?:?]
10.09 00:13:28 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.Menu.onMenuInteract(Menu.java:61) ~[?:?]
10.09 00:13:28 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor648.execute(Unknown Source) ~[?:?]
10.09 00:13:28 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
10.09 00:13:28 [Server] ERROR Could not pass event InventoryClickEvent to Civs v1.4.4
10.09 00:13:28 [Server] INFO java.lang.NullPointerException: null
10.09 00:13:28 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.RegionTypeInfoMenu.handleInteract(RegionTypeInfoMenu.java:35) ~[?:?]
10.09 00:13:28 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.Menu.onMenuInteract(Menu.java:61) ~[?:?]
10.09 00:13:28 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor648.execute(Unknown Source) ~[?:?]
10.09 00:13:28 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:28 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Multicraft] Skipped 85 lines due to rate limit (30/s)
10.09 00:13:32 [Server] ERROR Could not pass event InventoryClickEvent to Civs v1.4.4
10.09 00:13:32 [Server] INFO java.lang.NullPointerException: null
10.09 00:13:32 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.RegionTypeInfoMenu.handleInteract(RegionTypeInfoMenu.java:35) ~[?:?]
10.09 00:13:32 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.Menu.onMenuInteract(Menu.java:61) ~[?:?]
10.09 00:13:32 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor648.execute(Unknown Source) ~[?:?]
10.09 00:13:32 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
10.09 00:13:32 [Server] ERROR Could not pass event InventoryClickEvent to Civs v1.4.4
10.09 00:13:32 [Server] INFO java.lang.NullPointerException: null
10.09 00:13:32 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.RegionTypeInfoMenu.handleInteract(RegionTypeInfoMenu.java:35) ~[?:?]
10.09 00:13:32 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.Menu.onMenuInteract(Menu.java:61) ~[?:?]
10.09 00:13:32 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor648.execute(Unknown Source) ~[?:?]
10.09 00:13:32 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:32 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Multicraft] Skipped 16 lines due to rate limit (30/s)
10.09 00:13:34 [Server] ERROR Could not pass event InventoryClickEvent to Civs v1.4.4
10.09 00:13:34 [Server] INFO java.lang.NullPointerException: null
10.09 00:13:34 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.RegionTypeInfoMenu.handleInteract(RegionTypeInfoMenu.java:35) ~[?:?]
10.09 00:13:34 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.Menu.onMenuInteract(Menu.java:61) ~[?:?]
10.09 00:13:34 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor648.execute(Unknown Source) ~[?:?]
10.09 00:13:34 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
10.09 00:13:35 [Server] ERROR Could not pass event InventoryClickEvent to Civs v1.4.4
10.09 00:13:35 [Server] INFO java.lang.NullPointerException: null
10.09 00:13:35 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.RegionTypeInfoMenu.handleInteract(RegionTypeInfoMenu.java:35) ~[?:?]
10.09 00:13:35 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.Menu.onMenuInteract(Menu.java:61) ~[?:?]
10.09 00:13:35 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor648.execute(Unknown Source) ~[?:?]
10.09 00:13:35 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:13:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
10.09 00:13:36 [Server] INFO CONSOLE issued server command: /list 
10.09 00:13:36 [Server] INFO Admins: [HIDDEN]Axio__, Whisperer195
10.09 00:13:36 [Server] INFO Member: Eagleys24, MattMnz, Moochocho, xRiotLion
10.09 00:13:37 [Server] INFO Axio__ issued server command: /tp xRiotLion
10.09 00:13:49 [Server] INFO Axio__ issued server command: /tp xRiotLion
10.09 00:14:05 [Server] ERROR Could not pass event InventoryClickEvent to Civs v1.4.4
10.09 00:14:05 [Server] INFO java.lang.NullPointerException: null
10.09 00:14:05 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.RegionTypeInfoMenu.handleInteract(RegionTypeInfoMenu.java:35) ~[?:?]
10.09 00:14:05 [Server] INFO at org.redcastlemedia.multitallented.civs.menus.Menu.onMenuInteract(Menu.java:61) ~[?:?]
10.09 00:14:05 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor648.execute(Unknown Source) ~[?:?]
10.09 00:14:05 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1014) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1007) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:991) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:924) ~[patched_1.14.4.jar:git-Paper-137]
10.09 00:14:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201

**Comment by Multitallented** [comment]
Fixed! Turns out it was an issue with invalid regions during loading
