### ISSUE TITLE
Production is Broken. (Produces even without Requirements).

### ISSUE THREAD

**Issue by Blumiere** [Multitallented/Civs#4]
The item production Regions, are producing resources even without the required materials.
For example:

Cobblequarry:
Needs 1 Iron Pickaxe to produce 1 cobblestone every 10 seconds.
It produces the cobblestone without the pickaxe.

But it still takes the money from the owner.

Going to test a bit more, might find more info.

**Comment by Multitallented** [comment]
Could you please post your cobblequarry.yml in a pastebin?

**Comment by Blumiere** [comment]
Problem Fixed! Closing issue.

**Comment by Blumiere** [comment]
The problem is back.
Buildings produce items without reagents. 

Here is my config: https://hastebin.com/exayumuboq.http

**Comment by Blumiere** [comment]
But for a odd reason, Cobble Quarry works fine

I think its something to do with input.

**Comment by Blumiere** [comment]
Confirmed, its an issue with Input!

**Comment by Blumiere** [comment]
Fixed.
