### ISSUE TITLE
I lost the jade mine

### ISSUE THREAD

**Issue by nikissXI** [Multitallented/Civs#40]
I died in the end, and I lost it. Where can I get it again?

**Comment by L-Clockworker** [comment]
Buy a new one.
If you can't, check the blueprints menu.

**Comment by L-Clockworker** [comment]
Reopen if you still can't get it :)

**Comment by nikissXI** [comment]
I reopen it but I still can not get it :)

**Comment by L-Clockworker** [comment]
It won't allow you to buy a new one?

**Comment by nikissXI** [comment]
yes
