### ISSUE TITLE
Can not open the "region" menu

### ISSUE THREAD

**Issue by nikissXI** [Multitallented/Civs#45]
![image](https://user-images.githubusercontent.com/31379266/65380465-10f12d80-dd0f-11e9-9d6d-f7dc31ac9675.png)

Because too many(full) region in the "region" menu, so when I open it, it will close immediately. I suggest you add a "next page" button.

**Comment by L-Clockworker** [comment]
Good to know. Multi will get in contact soon, I'll make sure to send him a message about this.
Thanks!

**Comment by nikissXI** [comment]
thank you

**Comment by L-Clockworker** [comment]
@nikissXI 

This will be fixed in the next update (Custom Menus).
Thanks for your patience.
