### ISSUE TITLE
Error spamming console

### ISSUE THREAD

**Issue by whisperer195** [Multitallented/Civs#47]
01.10 23:25:12 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.RegionTickTask.onTwoSecondEvent(RegionTickTask.java:35) ~[?:?]
01.10 23:25:12 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor631.execute(Unknown Source) ~[?:?]
01.10 23:25:12 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:12 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:12 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.CommonScheduler.run(CommonScheduler.java:74) ~[?:?]
01.10 23:25:12 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:12 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:12 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:12 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:12 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:12 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
01.10 23:25:14 [Server] ERROR Could not pass event RegionTickEvent to Civs v1.5.1
01.10 23:25:14 [Server] INFO java.lang.NullPointerException: null
01.10 23:25:14 [Server] INFO at org.redcastlemedia.multitallented.civs.regions.effects.ConveyorEffect.isDestinationChestFull(ConveyorEffect.java:232) ~[?:?]
01.10 23:25:14 [Server] INFO at org.redcastlemedia.multitallented.civs.regions.effects.ConveyorEffect.onCustomEvent(ConveyorEffect.java:154) ~[?:?]
01.10 23:25:14 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor594.execute(Unknown Source) ~[?:?]
01.10 23:25:14 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.RegionTickTask.onTwoSecondEvent(RegionTickTask.java:35) ~[?:?]
01.10 23:25:14 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor631.execute(Unknown Source) ~[?:?]
01.10 23:25:14 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.CommonScheduler.run(CommonScheduler.java:74) ~[?:?]
01.10 23:25:14 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
01.10 23:25:16 [Server] ERROR Could not pass event RegionTickEvent to Civs v1.5.1
01.10 23:25:16 [Server] INFO java.lang.NullPointerException: null
01.10 23:25:16 [Server] INFO at org.redcastlemedia.multitallented.civs.regions.effects.ConveyorEffect.isDestinationChestFull(ConveyorEffect.java:232) ~[?:?]
01.10 23:25:16 [Server] INFO at org.redcastlemedia.multitallented.civs.regions.effects.ConveyorEffect.onCustomEvent(ConveyorEffect.java:154) ~[?:?]
01.10 23:25:16 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor594.execute(Unknown Source) ~[?:?]
01.10 23:25:16 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.RegionTickTask.onTwoSecondEvent(RegionTickTask.java:35) ~[?:?]
01.10 23:25:16 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor631.execute(Unknown Source) ~[?:?]
01.10 23:25:16 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.CommonScheduler.run(CommonScheduler.java:74) ~[?:?]
01.10 23:25:16 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:16 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

01.10 23:25:18 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.RegionTickTask.onTwoSecondEvent(RegionTickTask.java:35) ~[?:?]
01.10 23:25:18 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor631.execute(Unknown Source) ~[?:?]
01.10 23:25:18 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:18 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:18 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.CommonScheduler.run(CommonScheduler.java:74) ~[?:?]
01.10 23:25:18 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:18 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:18 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:18 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
01.10 23:25:20 [Server] ERROR Could not pass event RegionTickEvent to Civs v1.5.1
01.10 23:25:20 [Server] INFO java.lang.NullPointerException: null
01.10 23:25:20 [Server] INFO at org.redcastlemedia.multitallented.civs.regions.effects.ConveyorEffect.isDestinationChestFull(ConveyorEffect.java:232) ~[?:?]
01.10 23:25:20 [Server] INFO at org.redcastlemedia.multitallented.civs.regions.effects.ConveyorEffect.onCustomEvent(ConveyorEffect.java:154) ~[?:?]
01.10 23:25:20 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor594.execute(Unknown Source) ~[?:?]
01.10 23:25:20 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.RegionTickTask.onTwoSecondEvent(RegionTickTask.java:35) ~[?:?]
01.10 23:25:20 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor631.execute(Unknown Source) ~[?:?]
01.10 23:25:20 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.CommonScheduler.run(CommonScheduler.java:74) ~[?:?]
01.10 23:25:20 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:20 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
01.10 23:25:22 [Server] ERROR Could not pass event RegionTickEvent to Civs v1.5.1
01.10 23:25:22 [Server] INFO java.lang.NullPointerException: null
01.10 23:25:22 [Server] INFO at org.redcastlemedia.multitallented.civs.regions.effects.ConveyorEffect.isDestinationChestFull(ConveyorEffect.java:232) ~[?:?]
01.10 23:25:22 [Server] INFO at org.redcastlemedia.multitallented.civs.regions.effects.ConveyorEffect.onCustomEvent(ConveyorEffect.java:154) ~[?:?]
01.10 23:25:22 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor594.execute(Unknown Source) ~[?:?]
01.10 23:25:22 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.RegionTickTask.onTwoSecondEvent(RegionTickTask.java:35) ~[?:?]
01.10 23:25:22 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor631.execute(Unknown Source) ~[?:?]
01.10 23:25:22 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.CommonScheduler.run(CommonScheduler.java:74) ~[?:?]
01.10 23:25:22 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:22 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

01.10 23:25:24 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.RegionTickTask.onTwoSecondEvent(RegionTickTask.java:35) ~[?:?]
01.10 23:25:24 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor631.execute(Unknown Source) ~[?:?]
01.10 23:25:24 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:24 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:24 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:24 [Server] INFO at org.redcastlemedia.multitallented.civs.scheduler.CommonScheduler.run(CommonScheduler.java:74) ~[?:?]
01.10 23:25:24 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:24 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:24 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:24 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:24 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:24 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-137]
01.10 23:25:24 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by Multitallented** [comment]
I have a fix in for this. Should be out in the next update
