### ISSUE TITLE
Feature Request: Adjustable region boundaries

### ISSUE THREAD

**Issue by James-Thegiant** [Multitallented/Civs#48]
First off, absolutely love this plugin! It's really well done. I have a suggestion that I feel would massively improve the quality of life for the game. 
When placing down a structure it isn't always clear exactly where the region boundaries will end up being defined. If you really need to you can sometimes place required blocks in the extreme corners during construction but this is a kind of messy way of doing it and doesn't always work as you'd expect. It also doesn't help if you've already placed the regions down. It would be nice to be able to adjust the region boundaries within a certain range around the designating block.

One way this could represent as would be an option inside the region's menu, which would then have options for +x, -x, +y, -y, +z, and -z. I think this would make the most sense for this plugin.
Another that I've seen with some mods is to take a designated tool and right-click on the corner of the boundary and then right-click again where you'd like to move the boundary, which could also work.

To do this right, obviously this process would still need to check that all the required blocks for the region were still inside that region boundaries, and the region boundaries would not be able to move past the block that designates the region (thus preventing someone from slowly moving a region unreasonable distances).
This also wouldn't change the dimensions of the bounding region, it would transpose all 8 corners of the bounding box an equal amount in the same direction. I think it could be cool to be able to adjust the dimensions (making a 10x10 region able to be adjusted to a 12x8 or 14x7 region for instance) but that would be a separate process. Possibly able to be added on to this feature, but not as important in my eyes, and feels like it would be much more complicated to enact)

Cheers!

**Comment by Multitallented** [comment]
What if I created plots that you could build your region in. That way the region wouldn't exceed the bounds of the plot?
