### ISSUE TITLE
Minimum space between civ claims

### ISSUE THREAD

**Issue by AkiraKokiri** [Multitallented/Civs#49]
Before I start, I just want to say I LOVE this plugin! Everyone on my server is having a ton of fun with it so far. 

It would be really great to have a configuration setting to allow us to define a minimum distance in blocks/chunks each civ must be away from each other. Right now people can form a town right outside of another one and it's claim area overlaps the other civ. Something like the towny plugin that makes it so a town can't be claimed too close to another one to prevent blocking etc.

**Comment by AkiraKokiri** [comment]
![image](https://user-images.githubusercontent.com/5852502/66349370-ba970800-e926-11e9-8ea4-0d50703aa4c6.png)
This is an example of what I mean

**Comment by Multitallented** [comment]
This shouldn't be possible. Definitely a bug. I'll add the option to set a minimum distance in addition to fixing the bug. When setting a min distance, keep in mind that outposts need to be built within 150 blocks of the civ they are sieging

**Comment by Multitallented** [comment]
Fixed
