### ISSUE TITLE
Gold_Infuser reports "required blocks not placed" but gives no information on what blocks are needed

### ISSUE THREAD

**Issue by IlGnome** [Multitallented/Civs#53]
When building a gold infuser it will not place despite all required blocks being placed. When the gold_infuser chest is put into the civs blueprint menu it is no longer there and must be re-bought from the shop.

Civs version is 1.5.4

![2019-10-31_16 41 29](https://user-images.githubusercontent.com/10223460/67988370-c3b18700-fbfd-11e9-966e-d0d4900c8d69.png)
![2019-10-31_16 42 05](https://user-images.githubusercontent.com/10223460/67988371-c3b18700-fbfd-11e9-8099-10dbb1f6161b.png)
![2019-10-31_16 42 19](https://user-images.githubusercontent.com/10223460/67988372-c3b18700-fbfd-11e9-8345-14a1692b3209.png)

**Comment by Multitallented** [comment]
I'll look into this and hopefully have it fixed in the next update

**Comment by Multitallented** [comment]
Found the issue. It requires planted carrots that display as invisible in the requirements menu. They should show up properly now
