### ISSUE TITLE
Players spawn in another Players town with no relation to each other.

### ISSUE THREAD

**Issue by Malgaph** [Multitallented/Civs#66]
A player would kill themself several times and then randomly appear in another player's base with no relation between the two players. A player in my server is abusing this to troll other players by spawning in their base and attacking them when they least expect it. 

I have no clue why this occurs, the player has no bed spawn and is not apart of these player's towns. Not even as a guest.

**Comment by L-Clockworker** [comment]
@Malgaph , the Town that the player is respawning has a Graveyard?

**Comment by Malgaph** [comment]
@L-Clockworker The players who are affected by this are spawning in the council room of another town, and no one on my server has constructed a graveyard yet. What's mysterious is how it only seems to affect a small group of players and happens when a player of such group dies multiple times then suddenly spawns in a different place.

**Comment by L-Clockworker** [comment]
I suppose that you're running the Hybrid Default setup, right?
Or did you change any config?

**Comment by Malgaph** [comment]
Here is my config file, I don't believe I have changed anything major to plugin respawn function to cause this weird respawn behavior. 
[config.txt](https://github.com/Multitallented/Civs/files/4009086/config.txt)

**Comment by Multitallented** [comment]
Civs does not change the bed respawn location of a player unless the region has the "bed" effect. Only the shelter has that effect and it only works for the owner of the shelter. I'll check to see if attempting to place the shelter changes your bed spawn, but other than that I have no answer for you.

**Comment by Multitallented** [comment]
@Malgaph I can't fix this without more information. Sorry. Feel free to re-open this if you have anything to add.
