### ISSUE TITLE
Jammer trap does not work: No evidence of teleport interception

### ISSUE THREAD

**Issue by Malgaph** [Multitallented/Civs#67]
I have tested it in all cardinal directions with 3 different players and it has revealed that the Jammer trap to no extent changes their teleportation path. This has put many players on edge as now they cannot even expect their town to be safe from the abuse of the Hunters Lodge.

In addition, I want to know if a price or cooldown could be added to the Hunters Lodge to make it less abusable. Players use it in conjunction with ports to enter then a leave a persons area quickly. The combat cooldown isn't enough of a deterrent to being used as a way to counter its abuse.

**Comment by Multitallented** [comment]
I'll look into this. Maybe something broke in the patches since the Jammer was released.

As for the Hunting lodge, I'll make it run an upkeep from the region so that you can make it cost items, money, etc.

**Comment by Multitallented** [comment]
Fixed both. The Jammer Effect wasn't being instantiated properly. The hunt effect now runs upkeep and does not teleport the player unless at least one upkeep is successful

**Comment by Multitallented** [comment]
You'll need to modify the hunting-lodge.yml to give it an upkeep.
