### ISSUE TITLE
NPC dwellings and above are not counting for town population.

### ISSUE THREAD

**Issue by Malgaph** [Multitallented/Civs#69]
After a certain amount of npc's has been generated, subsequent npc housing will not generate more population.  Chatels and dwellings stop producing any more villagers. As you can see with two of the towns affected they have more than enough housing, even with barracks made. But as they create the chatels and houses to turn into npc population. They can't seem to get any higher than what seems to be 13 & 14. I have worked with them for a couple of days already and looked in the files for a limit to villagers, but I cannot find any.  Am I missing something in the config? 

I note that the buildings are made correctly to my knowledge as I am the admin to my server as was watching their creation. They had a successful operation and showed no missing blocks, but did not add anything to village population. 
[Civ Towns.txt](https://github.com/Multitallented/Civs/files/4009098/Civ.Towns.txt)
int

**Comment by Multitallented** [comment]
Chalet, Mansions, and Houses seemed to have been missing the villager effect. I've gone ahead and made those buildings spawn 2 villagers and provide 2 housing. Should be fixed now.
