### ISSUE TITLE
Suddenly destroyed region. (Persists)

### ISSUE THREAD

**Issue by Louis-BloodRose** [Multitallented/Civs#7]
Destroying a Region too fast (Creeper, Creative, etc), makes it to be destroyed but effect persists, and you won't be able to replace the region.

How to reproduce:

- Place region.
- Destroy region with TNT, Creeper, Creative.
- Try to replace the region.
- Try to see if effect still persists (Tested with Graveyard).

**Comment by Multitallented** [comment]
Posted a fix. Thanks for the testing!
