### ISSUE TITLE
Integrate Citizens2 ♥

### ISSUE THREAD

**Issue by drAkeEngine** [Multitallented/Civs#77]
It would be great if the citizens could be the sub administrators of the cities

that with them npc, the players could be invited or expelled or that work instead of the villagers.

Sorry for my bad english

**Comment by LF11** [comment]
You can use denizens, to program a command function then set the command in the regions you want a citizen to spawn. That is something I am trying to achieve on my server. They are working on more recent documentation for it, I would check their discord for most information: https://discord.gg/Q6pZGSR

**Comment by L-Clockworker** [comment]
We are not planning Citizens integration, sorry.
Closing it.
