### ISSUE TITLE
Not Showing the Price just "Price"

### ISSUE THREAD

**Issue by devilx1985** [Multitallented/Civs#79]
Hi, 

Civs is not showing the price number, just "Price".

Im using latest version of Civs. 
Paper 1.15.1-50
LuckPerms
Vault
GemsEconomy

**Comment by Multitallented** [comment]
I'm sorry, but this is not enough information to reproduce this bug. Where is this happening? What menu? Do you have a screenshot? Please re-open this issue with more information.

**Comment by devilx1985** [comment]
Sorry, yes. 

With the book in hand, right click >> shop >> Select any category >> hoover over the item >> shows "Price" instead of actual price $$$. 

![CivsNotShowingPrice](https://user-images.githubusercontent.com/13035328/72686755-8c949880-3abd-11ea-8d6d-cea5680673a7.PNG)

Even if you click the item, in the "For sale" icon, keep showing "Price" instead of the amount. 

![CivsNotShowingPrice2](https://user-images.githubusercontent.com/13035328/72686792-ce254380-3abd-11ea-95dc-3eb3b1bd8594.PNG)

Thank you in advance.
