### ISSUE TITLE
Building Blocks Requirements (Missing)

### ISSUE THREAD

**Issue by Louis-BloodRose** [Multitallented/Civs#8]
If the region has lots of Block Requirements, it wont show all of them.
The menu of requirements is correct, the only problem is with the text shown when you try to place the build.

- Create a region with lots of materials reqs (item-groups).
- Try to place the region.
- It will show that its missing one of the reqs, but its not the true req. 
- No matter how many times you place the block it says its missing, it will keep giving you the same msg.

**Comment by Multitallented** [comment]
Clarification, there's a bug with config.yml item-groups. Can't recognize multiple door items in a single group

**Comment by Multitallented** [comment]
Further clarification, it's an error with the message. If you are missing other requirements, it will tell you a door is missing even if you have the doors placed

**Comment by Multitallented** [comment]
Config.yml https://pastebin.com/1LMXJjHb
Region in question: https://pastebin.com/RK4T0x0w

**Comment by Multitallented** [comment]
I've released a fix for this issue
