### ISSUE TITLE
Civs showing "Price" instead of actual price $$$

### ISSUE THREAD

**Issue by devilx1985** [Multitallented/Civs#81]
Hi,

Civs is not showing the price number, just "Price".

Im using latest version of Civs.
Paper 1.15.1-50
LuckPerms
Vault
GemsEconomy

With the book in hand, right click >> shop >> Select any category >> hoover over the item >> shows "Price" instead of actual price $$$. 

![CivsNotShowingPrice](https://user-images.githubusercontent.com/13035328/72686755-8c949880-3abd-11ea-8d6d-cea5680673a7.PNG)

Even if you click the item, in the "For sale" icon, keep showing "Price" instead of the amount. 

![CivsNotShowingPrice2](https://user-images.githubusercontent.com/13035328/72686792-ce254380-3abd-11ea-95dc-3eb3b1bd8594.PNG)

Thank you in advance.

_Originally posted by @devilx1985 in https://github.com/Multitallented/Civs/issues/79#issuecomment-576036786_

**Comment by Multitallented** [comment]
I'm still not able to reproduce this for some reason. Works for me using the default configs. I'll keep this open in case I think of something else.

**Comment by Multitallented** [comment]
Fixed!
