### ISSUE TITLE
No playerlist menu

### ISSUE THREAD

**Issue by LoJoSho** [Multitallented/Civs#82]
There is no playlist menu available. 

In the community.yml, we see it posted there:

 players:
    index: 3
    icon: OAK_SIGN
    name: players
    actions:
      - menu:player-list

Then, if we go over to menus, there is no player-list
[https://i.gyazo.com/1e008f6ee831069a0187034bd04811e7.png](url)

Version: Civs 1.6.3

**Comment by Multitallented** [comment]
Fixed. It works in the default configs. You can use -menu:people
