### ISSUE TITLE
Dupe Bug Found

### ISSUE THREAD

**Issue by BenjaminHerrera** [Multitallented/Civs#84]
Hello!

Recently, I experienced a new issue with the Civs plugin. The server that I play on is on 1.15.2 and is running the latest version of the plugin. The issue that I talking about is a duping glitch whenever a player disconnects and then reconnects. By disconnecting and reconnecting, farms, mines, quarries, and utilities dupe the contents in it without using up the input resources. This is a pretty big issue as one can easily obtain chestfuls of TNT and other valuable resources. If a quick update can be pushed, this would help out a lot of servers that use the plugin. Thank you for reading and have a nice day!

- Ben

**Comment by Multitallented** [comment]
Fixed in v1.6.5
