### ISSUE TITLE
Civs items disappear after stacked with original items

### ISSUE THREAD

**Issue by leavessoft** [Multitallented/Civs#87]
![E2F59648-814D-4E1E-A327-B3178611831D](https://user-images.githubusercontent.com/7609740/74649020-bbd01f80-51b9-11ea-999d-dc5709327608.png)
![F4FF001D-07A1-4A0E-A7B8-81194EC55505](https://user-images.githubusercontent.com/7609740/74649024-bd99e300-51b9-11ea-931f-7a4d89dfefec.png)

For example, when a player attempt to stack the council room with a minecraft:obsidian, both of these two items will disappear after closing and re-opening the inventory.

I’d appreciate it if it is possible to prevent stacking Civs items with the original ones.

**Comment by L-Clockworker** [comment]
Might have to investigate this, i thought you couldn't stack 'lore items' with 'non lore items'. 
Can you input me a few steps on how to reproduce?

**Comment by leavessoft** [comment]
Thank you so much for investigating into this issue. Here's how I reproduce it:
![Civs_bugReport](https://user-images.githubusercontent.com/7609740/74848179-67bc6b00-5372-11ea-8b99-e809a2fe858f.gif)

**Comment by RumiExMachina** [comment]
Answered on discord. 
Waiting for response. :)

**Comment by Multitallented** [comment]
The council room is in your blueprints menu.
