### ISSUE TITLE
New Option: Force_Tutorial

### ISSUE THREAD

**Issue by LoJoSho** [Multitallented/Civs#94]
When you first join the server, you are presented with an option to opt into the tutorial or not. 

However, the confirmation screen gives no indication on what the screen is for and therefore, lots of players don't hit confirm which confuses the player as they have no sense of direction.

Solution: Option to force players into the tutorial in the config.yml.

It would be a simple option in the config that would simply say:

> force_tutorial: false #Should a player be forced to enter the tutorial on join?

This would be a simple yet amazing feature to have!

**Comment by Multitallented** [comment]
I can't think of a good reason to keep it in actually. I've just removed the menu
