### ISSUE TITLE
Members can kick owners, owners can't manage members

### ISSUE THREAD

**Issue by Miky88** [Multitallented/Civs#97]
The title say everything, tryed with all gov types.

**Comment by Miky88** [comment]
also members are able to set the owner as guest

**Comment by Multitallented** [comment]
Fixed in v1.6.6+

**Comment by Miky88** [comment]
there's even no 1.6.6 version

**Comment by minus1over12** [comment]
1.6.6 isn't released yet. @Multitallented meant to say that it will be fixed when that version is released.

**Comment by Miky88** [comment]
ahh that's nice. thank you sir
