### ISSUE TITLE
Allow Biome Restricitons to Work on Town Regions

### ISSUE THREAD

**Issue by minus1over12** [Multitallented/Civs#98]
The "biomes" build requirement is ignored on town regions.

**Comment by Multitallented** [comment]
I don't recommend this. Usually people build structures before they build the town region. Those structures should require the biome so as to tell the player sooner that their plans require a biome.

If you're building a town without structures, then I will still add this feature

**Comment by minus1over12** [comment]
I think that setup is probably a better idea, I'll do that instead.
